import express from 'express';
import multer from 'multer';
import { signup, verifyOTP, setPassword, login, saveStudentProfile, generateToken, verifyToken, getUserProfile, submitLeaveApplication, getLeaveSummary, getStudentScholarships, getEnjoyedLeaves, getAutoGeneratedLeaves, getGuideLeaveApplications, getGuideStudents, guideActionOnLeave, getOperatorLWPApplications, operatorActionOnLeave, getPendingStudents, approveRejectStudent, getAllStudents, toggleStudentStatus, uploadProfilePhoto, updateStudentProfile, addGuide, addCoGuide, getAvailableGuides, getAllGuides, batchTransferStudents, getMonthlyReport, getGuideMonthlyReport } from '../controllers/authController.js';

const router = express.Router();

// Configure multer for profile photo uploads
const upload = multer({
    storage: multer.memoryStorage(),
    limits: {
        fileSize: 5 * 1024 * 1024, // 5MB limit
    },
    fileFilter: (req, file, cb) => {
        const allowedTypes = ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'];
        if (allowedTypes.includes(file.mimetype)) {
            cb(null, true);
        } else {
            cb(new Error('Invalid file type. Only JPEG, PNG, and GIF images are allowed'), false);
        }
    }
});

// Configure multer for PDF document uploads (for DL leaves)
// Use memoryStorage for Vercel compatibility (filesystem is read-only on Vercel)
const uploadLeaveDocument = multer({
    storage: multer.memoryStorage(),
    limits: {
        fileSize: 5 * 1024 * 1024, // 5MB limit
    },
    fileFilter: (req, file, cb) => {
        const allowedTypes = ['application/pdf'];
        if (allowedTypes.includes(file.mimetype)) {
            cb(null, true);
        } else {
            cb(new Error('Invalid file type. Only PDF files are allowed'), false);
        }
    }
});

router.post('/signup', signup);
router.post('/verify-otp', verifyOTP);
router.post('/set-password', setPassword);
router.post('/login', login);
router.post('/student/saveStudentProfile', saveStudentProfile);
router.post('/student/uploadProfilePhoto', upload.single('profilePhoto'), uploadProfilePhoto);

// Token-related routes
router.post('/generate-token', generateToken);
router.get('/verify-token', verifyToken);
router.get('/user-profile', getUserProfile);

// Leave application routes
router.post('/student/submitLeaveApplication', uploadLeaveDocument.single('document'), submitLeaveApplication);
router.get('/student/leave-summary', getLeaveSummary);
router.get('/student/scholarships', getStudentScholarships);
router.get('/student/enjoyed-leaves', getEnjoyedLeaves);
router.get('/student/auto-generated-leaves', getAutoGeneratedLeaves);

// Guide routes
router.get('/guide/leave-applications', getGuideLeaveApplications);
router.get('/guide/students', getGuideStudents);
router.post('/guide/leave-action', guideActionOnLeave);

// Operator routes
router.get('/operator/lwp-applications', getOperatorLWPApplications);
router.post('/operator/leave-action', operatorActionOnLeave);

// Student management routes for operators
router.get('/operator/pending-students', getPendingStudents);
router.post('/operator/approve-reject-student', approveRejectStudent);
router.post('/operator/update-student-profile', updateStudentProfile);
router.get('/operator/all-students', getAllStudents);
router.post('/operator/toggle-student-status', toggleStudentStatus);

// Guide management routes for operators
router.post('/operator/add-guide', addGuide);
router.post('/operator/add-co-guide', addCoGuide);
router.get('/operator/all-guides', getAllGuides);
router.post('/operator/batch-transfer', batchTransferStudents);

// Report generation route for operators
router.get('/operator/monthly-report', getMonthlyReport);

// Report generation route for guides
router.get('/guide/monthly-report', getGuideMonthlyReport);

// Get available guides (for student form)
router.get('/available-guides', getAvailableGuides);

export default router;